version: '3.4'

networks:
  demoblazorapp:
    driver: bridge

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@ssw0rd2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  bloggi.web:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - BloggieDBConnectionString=Server=db;Database=datamvc;User Id=sa;Password=P@ssw0rd2024!;

    depends_on:
      - db

volumes:
  mssql_data:
